### PR TITLE
EIP1559 SUPPORT

### PR DESCRIPTION
**Pull request by sc0Vu**
EIP1559 SUPPORT #33 

Change log: 
- Remove space from composer.json
- Remove syntaxCheck from phpunit.xml
- Update .gitignore
- Add EIP2930 transaction
- Add EIP1559 transaction
- Refactor
- Update document

### CODE REVIEW

**Comment by kaimuns950619** [comment]
Hi, may i know when this version will be release in order to Support EIP1559 transaction?

**Comment by sc0Vu** [comment]
Hi @kaimuns950619 

I traced web3.py and ethereumjs-tx source code and found that I missed these EIPs in current implementation:

- [x] EIP2718

- [x] EIP2930

- [x] EIP1559

I'm going to implement these EIPs before EIP1559. Guess I can finish in this week.

**Comment by sc0Vu** [comment]
I've test type1 and type2 tx on rinkeby testnet, here is the transaction: 

Type1: https://rinkeby.etherscan.io/tx/0xf47d05ded68391f95bc507d1e6808d8c41b730542791cea1fd76417689ef37a5

Type2: https://rinkeby.etherscan.io/tx/0x4c143d84c977dfc697482bacf980ec7807057866a9e11e9107b322a99356df9e

Also write `web3.php` in the transaction data, it was fun.

**Comment by kaimuns950619** [comment]
@sc0Vu Noted with thanks

**Review by Gilg4mesh — APPROVED** [review]

**Pull request merged**
